apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: go-ps
  labels:
    app: go-ap
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    com.docker.project: hello-go
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: go-ps
  labels:
    com.docker.project: hello-go
spec:
  replicas: 2
  selector:
    matchLabels:
      com.docker.project: hello-go
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        com.docker.project: hello-go
    spec:
      containers:
        #- image: ghcr.io/argosenpaikun/hello-go:latest
        - image: ${IMAGE}
          name: hello-go
          ports:
            - containerPort: 8081
              protocol: TCP
      imagePullSecrets:
        - name: regcred