apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: go-ps
  labels:
    app: go-ap
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    com.docker.project: hello-go
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: go-ps
  labels:
    com.docker.project: hello-go
spec:
  replicas: 4
  selector:
    matchLabels:
      com.docker.project: hello-go
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # Default value is 25%
      # maxUnvailable is an optional field that specifies the maximum number of Pods that can be unavailable during the update process
      maxUnavailable: 20% # The value can be an absolute number (for example, 5) or a percentage of desired Pods (for example, 10%)

      # maxSurge is an optional field that specifies the maximum number of Pods that can be created over the desired number of Pods.
      maxSurge: 20% # The value can be an absolute number (for example, 5) or a percentage of desired Pods (for example, 10%)
  template:
    metadata:
      labels:
        com.docker.project: hello-go
    spec:
      containers:
        #- image: ghcr.io/argosenpaikun/hello-go:latest
        - image: ${IMAGE}
          name: hello-go
          ports:
            - containerPort: 8081
              protocol: TCP
      imagePullSecrets:
        - name: regcred