apiVersion: v1
kind: Namespace
metadata:
  name: psql-ps
  labels:
    team: prod-team
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: psql-ps
  labels:
    app: postgres
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_PASSWORD: SecurePassword