name: Docker Image CI

on:
  push:
    branches: [ "master", "release-1.0.1", "release-1.0.2", "release-1.0.3" ]
  pull_request:
    branches: [ "master", "release-1.0.1", "release-1.0.2", "release-1.0.3" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-go:latest
